### ISSUE TITLE
Add BGG Weights and PlayingTime to Point System

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#164]
Use the AverageWeight (decimal value from 1 to 5) and PlayingTime (minutes) to change the nemepoints earned for this game.

The more playingtime more points must be earned.
If the game it's short (less than 45 minutes?) must worth less points.

And the same for the weight. If it's less than ¿2? must worth less than a game with weight greater than 3.5

Also, we need to show this on GameDefinition view (a well floating at the right with the weight, playing time and BGG rating?)

Should also show a little info (?) tip next to each Player Game Result showing the breakdown of points. Something like (+19 Base Points +3 Game Duration +5 Game Weight)

**Comment by vfportero** [comment]
Blocked by #275

**Comment by jakejgordon** [comment]
So much activity on this one... survey is out there and BGG thread: http://boardgamegeek.com/article/22040060#22040060  Waiting to see how that pans out before finishing the implementation.
