### ISSUE TITLE
Remove Extra "|" in footer

### ISSUE THREAD

**Issue by dsilva609** [NemeStats/NemeStats#179]

**Comment by dsilva609** [comment]
Took a look at master and production, what is supposed to be between the pipes "| |" is the Follow Nemestats Twitter button, but for some reason this only shows up on my local master copy and not in production

**Comment by dsilva609** [comment]
Looked into this again, and it seems to be tied in to having an AdBlock/Plus extension enabled in the browser

**Comment by jakejgordon** [comment]
Closing per last comment.
