### ISSUE TITLE
BGS - Ability To Register Through Board Game Stats

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#191]
As an existing user of Board Game Stats without a NemeStats account, I can link my account to NemeStats so that I can get a new Gaming Group, User, and Player created automatically.

- The app should support registering via this service: http://docs.nemestats.apiary.io/#reference/authentication/user/register-a-new-user
- There will be no other functionality as part of this feature other than the linking of the accounts and the storing of the Gaming Group Id and Gaming Group Name in the app. Subsequent features will layer in more functionality.

**Comment by eerkov** [comment]
Tested all error-paths (existing username, existing email address, empty/invalid email address).
Creating account does return a status 500 at this point, account was created but email not sent.

**Comment by jakejgordon** [comment]
Yeah, I can reproduce the issue in production (but not locally). Must be something with how I have this configured in Azure.  Looking into it now, but might not get it resolved until tonight.
