### ISSUE TITLE
BGS - Ability For Existing NemeStats Users To Link Board Game Stats To NemeStats

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#194]
As an existing user of NemeStats, I can link my Board Game Stats app to my NemeStats account so that my plays can automatically be pushed and pulled between the applications.

- The app should allow the user to enter their NemeStats credentials which would call the http://docs.nemestats.apiary.io/#reference/authentication/user-session/create-a-new-user-session service to log in
- The purpose of this feature is only to allow the user to get a valid authentication token which it can pass on subsequent web service calls. It should also somehow indicate to the user that they are currently "logged in" to NemeStats.

**Comment by eerkov** [comment]
Logging in works without problem. 
Todo: save authenticationToken in defaults for use in later sessions.
