### ISSUE TITLE
Don't use Google Analytics Event Tracking locally

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#243]
Contributors shouldn't have to worry about this blowing up.

**Comment by jakejgordon** [comment]
Ended up only needing to add the google analytics app setting to the main web.config (instead of relying upon the PrivateAppSettings.config). New contributors shouldn't have the problem again.

**Comment by eerkov** [comment]
Hi, 

I'm sure you are interested in such info, be prepared for something really  great! More info here <http://folder.plaxco-davidson-home.com/e4wrt>

Eerko
