### ISSUE TITLE
[BUG] Player registered bool unchecked when name is changed

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#245]
I edited my name and the check for "Registered" has disappeared allowing me send an invitation when I already registered

**Comment by vfportero** [comment]
My nemesis has disappeared too

**Comment by jakejgordon** [comment]
Will try to check it out tonight. Thanks for reporting!

**Comment by jakejgordon** [comment]
Hi Victor, let me know if you have any issues with this. Hopefully I didn't leave you hanging!
