### ISSUE TITLE
Migrate all CSS to SASS

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#264]
Work with css it's uncomfortable. We can migrate all to saas easily to improved the maintenance of the style code.

what do you think?

**Comment by jakejgordon** [comment]
I'm all for it. I think we already have it introduced, but we'd  have to ask @cracker4o about it since I've tried to stay away from the styling as much as we can. Just look in UI/sass/ folder.

**Comment by vfportero** [comment]
HI @cracker4o ! I'm Víctor, the new guy in the neighbourhood :P 
I think that you are the responsible of the UI so I prefer talk with you before change a single line.

What do you think about migrate all the css to saas? The process is simple: copy all to a .scss file (we can use a css to sass converter to improve indentation and remove duplicities if you want) and use a compiler (I use Web Compiler: https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c but we'll could integrate more complicated tools like grunt).

**Comment by cracker4o** [comment]
It is a good idea. When we started we had a very different UI. After that I added a new bootstrap sass theme but we didn't migrate our existing CSS to sass. I would prefer Grunt but basically any change we'll be an improvement. Sass is easy to maintain and improves reusability. +1 from me.

**Comment by vfportero** [comment]
Closed in #286
