### ISSUE TITLE
Deactivating players adds weird champion results

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#267]
Charles Cai is a former Champion of Small World even with 0 wins. It looks like this record gets created when all other  players that have played  the game are de-activated. In this case, it probably makes more sense to not award a championship. Probably have this problem in the first game of Pandemic if everyone loses.

**Comment by jakejgordon** [comment]
After a player is de-activated, the next time a game is recorded the championship will switch over to a new player.

**Comment by vfportero** [comment]
nice!
