### ISSUE TITLE
Get the Game Stats from BGG Api2 for use the averageweight in NemePoints calculation

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#275]
Get the StatisticsObject from the BGG Api2. 
Example Api call URL: https://www.boardgamegeek.com/xmlapi2/thing?id=2536&type=boardgame&stats=1

This object is usefull for several background tasks like the NemePoints calculation

**Comment by jakejgordon** [comment]
Assigned this to myself not realizing that we aren't yet pulling the weight from the API. I'm going to take a different feature instead -- pulling out BGG information into a common table instead of denormalizing it everywhere. This will also simplify some other future features.

**Comment by vfportero** [comment]
This one it's solved on https://github.com/NemeStats/NemeStats/commit/db47603a20401a50abbdebf1ce802c19a5ccecc2

**Comment by vfportero** [comment]
It's not solved already. We need to add the follow properties to BoardGameGeekGameDefinition:

- Weight
- Playing Time
- Players
