### ISSUE TITLE
Sort GameDefinitions by Played Games in GamingGroup Details view

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#276]
What do you think about sort gamedefinitions by plyed games count instead name in gaminggroup details view?

https://nerdscorekeeper.azurewebsites.net/GamingGroup/Details/1

I think it's more comprehensible

**Comment by jakejgordon** [comment]
Just have to consider that some people have 50+ games so we want the experience good for them too. I'm indifferent I think.

**Comment by vfportero** [comment]
Maybe adding a js filter it's a good solution for this cases (something like this: http://www.listjs.com/).
Not only for game but also for players.

**Comment by vfportero** [comment]
I'm going to solve this and add the filter as other issue :)
