### ISSUE TITLE
Display Board Game Geek thumbnail everywhere it makes sense

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#277]
... like on the played game details and game definition details pages.

**Comment by vfportero** [comment]
I added the thumbnail to the home page widget making this section grow. To balance this I change the Top Gaming Group widget adding the champion and extending items to 15:

![captura](https://cloud.githubusercontent.com/assets/1107782/10894953/c5f9b296-81b1-11e5-8c7c-1846d6f130ca.PNG)

Maybe it's to much information... but, in other hand, makes the "last played games" widget more attractive.
What do you think?

**Comment by jakejgordon** [comment]
I think it looks good. We just need to get more diverse city and more big gaming groups up there!
