### ISSUE TITLE
Show the Player vs Player data in Player detail view as a stacked progress bar

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#284]
To improve the Look&Feel and the understanding of the data i think would be great show the "Win - Loss Record vs. Player" data as stacked progress bars like this:

![captura](https://cloud.githubusercontent.com/assets/1107782/10788689/6f22ba62-7d79-11e5-85e2-a3d098fe9a96.PNG)

(is a mockup hardcoded directly from Chrome Developer Tools.. the final style and color remains pending)

**Comment by jakejgordon** [comment]
Love it!

**Comment by vfportero** [comment]
closed in #287
