### ISSUE TITLE
A few flipscroll issues

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#304]
Attached are some screenshots of some minor issues I found when trying to test this thoroughly. Otherwise I think it looks great!

![flip_scroll_issue_5](https://cloud.githubusercontent.com/assets/3045786/11290659/cdac8100-8f06-11e5-9efe-8f81ff181229.jpg)
![former_champion_strikethrough_issue](https://cloud.githubusercontent.com/assets/3045786/11290660/cdad5706-8f06-11e5-86b3-a6580b066359.jpg)
![flip_scroll_issue_4](https://cloud.githubusercontent.com/assets/3045786/11290662/cdb5047e-8f06-11e5-91fd-17b2c9c7af72.jpg)
![flip_scroll_issue_3](https://cloud.githubusercontent.com/assets/3045786/11290661/cdb4e5e8-8f06-11e5-95d4-4fb0c709066f.jpg)
![flip_scroll_issue_2](https://cloud.githubusercontent.com/assets/3045786/11290663/cdbd1b14-8f06-11e5-91bd-6a9316f08861.jpg)
![flip_scroll_issue_1](https://cloud.githubusercontent.com/assets/3045786/11290664/cdbfb6f8-8f06-11e5-91bf-23a6d330c9e5.jpg)

**Comment by vfportero** [comment]
Solved.

I've removed the flipscroll style for the GameDefinition Result table. Too much information fir this kind of table... for that case is better the vertical classic table
