### ISSUE TITLE
Redesign the Home Page

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#306]
![screencapture-nerdscorekeeper-azurewebsites-net-1447860512409](https://cloud.githubusercontent.com/assets/1107782/11295659/52f87bb4-8f6d-11e5-907e-5c119d9c2567.png)

I've been thinking about the home page redesign and this is the first mockup that i propose.
The main banner it's wasted right now. We need a POWERFULL claim and call to action.

On the one hand, use a similar image of the kickstarter campaing with a board game background and a clear and strong main message: "BOARD GAME TRACKING MADE FUN!" as banner
On other hand the CTA must be the social login to quickly enter/register to the site.

If you are already logged we can fill that slot with quick access to your gaming group, your profile or quick stats (like 4 big numbers with your Nemepoints, championships, minions and games played)
or maybe a big button to register new played game.

Anyway, this CTA is the most important element on the page.

I prefer the Claim on the left and the CTA on the right but the sample image has this layout so i used it to show you ;-)

After the banner we display the 3 current features to extend the understanding of the site for the new users.

This features can be in a carrousel like now if you want.
The current long explanation must be hidden by default (in the second carrousel page or in a About page) because is too long to read :(

Then, the 4 plugins section like now.

I've changed the top menu color to add the image logo instead text as the logo is black we need a clear background.
I've used the current green color but i dont like it... it just want to show you the contrast effect with the banner and the image logo.

Also, i would add a "explore" menu to encourage the visitors to discover our site including links to recent plays, top players, top gaming group, global games, etc...

On Mobile:
Claim must go first, then the CTA with the login.

I've added (as idea :P) the FB login. Could be a great improvement to easily convert new users (and get their avatars!)

**Comment by vfportero** [comment]
@jakejgordon I need the base image of this design: https://github.com/NemeStats/NemeStats/blob/master/Social/AlternateTwitterHeader.png

The full image without any text. Can you get it for me? Thanks :)

**Comment by jakejgordon** [comment]
Hopefully tomorrow I can!
