### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by mkoch227** [NemeStats/NemeStats#309]
I was just trying to log in, but I was greeted with an error message. The error being logged is at https://rollbar.com/jakejgordon/NemeStats/items/2192/?item_page=0&#instances.  The error message in the log is "RuntimeBinderException: 'object' does not contain a definition for 'Action'"

**Comment by jakejgordon** [comment]
Thanks Mike -- Victor and I are looking at it right now actually. Just had
a bad deploy. Will hopefully have it fixed soon.

**Comment by jakejgordon** [comment]
Is it working now?

**Comment by mkoch227** [comment]
Yep, it's working. Thanks!
