### ISSUE TITLE
Javascript issue adding players

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#326]
See attached media. This happens in Chrome and also in incognito mode.

**Comment by jakejgordon** [comment]
Looks like the video didn't attach. I can't recreate this so far, but I suspect the problem is in createplayedgame.js in the addPlayer function. Somehow clearing the selected player is triggering the onchange event of the drop-down or something.

**Comment by vfportero** [comment]
I saw the video, don't worry. I try to fix it today or tomorrow :S
