### ISSUE TITLE
Filter gaming group stats by date

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#327]
Feature suggested on http://nemestats.idea.informer.com/proj/?ia=99967

Add a method to filter all Gaming Group stats between two dates (nol filter by default)

**Comment by jakejgordon** [comment]
I'm 95% done with the functionality. Could definitely use some help with making the front end look a little nicer. Also debating whether we need to show in each section the date range being filtered (e.g. Players, Game Definitions, Played Games could have something like "2015-06-01 through 2015-06-30" if you are filtering on that range.

**Comment by vfportero** [comment]
Don't worry Jake, i can face off with the UI ;-)
