### ISSUE TITLE
Font awesome is throwing a 404

### ISSUE THREAD

**Issue by cracker4o** [NemeStats/NemeStats#338]
When you go to any page, the request for font awesome fails with a "Failed to load resource" error.

This is the problematic URL:
https://nerdscorekeeper.azurewebsites.net/fonts/fontawesome-webfont.woff2?v=4.4.0

**Comment by vfportero** [comment]
mmm, this file exist in the repo but not in production site. Checking it...

**Comment by vfportero** [comment]
Solved on https://github.com/NemeStats/NemeStats/commit/544204daf8f6872dfc01f99c1a4b4055fbeacd4d

**Comment by vfportero** [comment]
Thanks for the warning Tosho :)
