### ISSUE TITLE
As a user, i want to see a Leaderboard in the GameDefinition view

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#340]
The "Win - Loss Statistics" panel is not very useful.
I've asked to several players and all tell me than a leaderboard (like the main gaming group) filtered for this game in particular will be better

**Comment by jakejgordon** [comment]
Is average points per game and total NemePoints the only thing missing in the Players panel?

**Comment by vfportero** [comment]
Points, games played, avg points and win ratio.

We can join the "Champion" and "Win - Loss Statistics" panels to "Players" showing a table like the gaming group:

- Champion / Former champion badge
- Player name
- NemePoints earned playing that game
- Played Games
- Avg. points per game
- Winned games (and %)
