### ISSUE TITLE
As a developer, I want a Azure Job to update all the GameDefinition with current BGG values

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#364]
Once per week? per day?

Also create other job to cleanup gamedefinitions without bggid

**Comment by jakejgordon** [comment]
I think this could run once per week and would be just fine. Another option is that we just update it whenever someone adds the game to their gaming group. Then we wouldn't even need a job. The downside would be that if someone adds a game before BGG really has the stats for it then they could be stuck with outdated play time and weight

**Comment by vfportero** [comment]
Looking the BGG api errors i think we need to do this cleanup often as a job. This job must do:

- Look for incomplete BGG games (null images, 0 or null weight/playing time, players...) and update from BGG api
- Look for GameDefinitions not related wit BGG and try to search their Id (looking for an exact search of the game name)

To avoid errors on BGG client we have to implement some kind of retry policy with a little time between request

**Comment by vfportero** [comment]
There are games without weight, playing time or image (https://boardgamegeek.com/boardgame/23887/rage-game). Study about how to deal with this
