### ISSUE TITLE
As user, I want to have a better Record Play form

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#368]
Improve the current record play form adding a "guided" process:

## 1. Select game and date
Create a game selector showing a block with:
- Recent games
    - usefull to record several plays of the same game
- More played games
    - it's more probable that the user wants to record a play of a game widely played than others without play
- Full game list with search box
    - maybe using select2:  http://select2.github.io/examples.html#templating
- Create new game 
    - same input with autocomplete & search using the BGG api

Also, show the calendar to set the date (today by default)
## 2. Select Players
Show two side-by-side panels to select the players involved on this play (a component like this: http://crlcu.github.io/multiselect/) with a search box and grouped by:

- You
    - In most cases the same user that records the play is a player. Show their player (it has) in an optgroup
- Recent players
    - Show the last recorded game players. It's probably that this players are participating on this play too.
- Other players
    - Sorted alphabetically and searchable
- Create new player
    - Input to create new player and add it to the "players" list.

## 3. Select game type
Show 2 big buttons to select the game type:
- Ranked Game
- Cooperative Game
## 4.1 If is a Cooperative Game
Show 2 big buttons to select the winner type:
- Everyone Won
- Everyone Lose

Add the "notes" textarea.

## 4.2 If is a Ranked Game
Show the player list similar to the current one.
Sorted in the same order than the player select on the list.
Possibility to set the score (this must reorder the list) and establish the rank manually (like now).

Add the "notes" textarea.

## 5 Ajax POST and Success view
Make the POST via ajax to avoid problems notifiying new achievements or other stuff.

The success view must show a big green success block with 3 action buttons:

1. Record other play
2. Go to main gaming group page
3. Share on twitter 
    - Like the current one on the play details view: https://twitter.com/intent/tweet?hashtags=boardgames&original_referer=https%3A%2F%2Fnemestats.com%2FPlayedGame%2FDetails%2F42812&ref_src=twsrc%5Etfw&related=nemestats&text=Check%20out%20this%20game%20I%20played%20on%20%40nemestats%20%3A&tw_p=tweetbutton&url=https%3A%2F%2Fnemestats.com%2FPlayedGame%2FDetails%2F42812

**Comment by jakejgordon** [comment]
I really like it. Would really just need to see more to have an opinion about the details of how it is presented!

**Comment by jakejgordon** [comment]
Would it make sense to also try to incorporate the ability to record points? This could be another  game type -- "Rank based on player points": http://nemestats.idea.informer.com/proj/?ia=101905

I'm sure we could add that as a separate feature if that makes sense. It is the #1 requested feature though :)

**Comment by vfportero** [comment]
Yep, it's planned ;-)
