### ISSUE TITLE
Add NemePoints breakdown everywhere

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#384]
As a user, I can see the breakdown of NemePoints wherever I see the signature NemePoints icon, so that I can see how many points were from game weight and game duration.

**Comment by vfportero** [comment]
Also we need to check all the width breakpoints on NemePoints:

![image](https://cloud.githubusercontent.com/assets/1107782/14344761/dd62fef6-fca9-11e5-88ab-92d3db0d07a7.png)


Also check this: 
![pasted image at 2016_04_06 07_36 am](https://cloud.githubusercontent.com/assets/1107782/14344599/deddbc04-fca8-11e5-96dc-479063dfc219.png)

**Comment by jakejgordon** [comment]
My thought is that a tooltip that you can toggle might work best in most scenarios, but i'll trust your judgment.
