### ISSUE TITLE
Place Board Game Stats Widget on Home page and Record a Game page

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#394]
We need to place a widget promoting Board Game Stats as an iOS app which can record games and sync them to NemeStats. It should have the logo and some text like this:

"Board Game Stats is  the premier iOS app for recording the results of board games. It now comes with the ability to import your NemeStats Players and Game Definitions directly into the app. You can also push your plays from the app directly back into NemeStats! 

Simply configure your NemeStats credentials from the main settings screen and the rest should be intuitive."

**Comment by vfportero** [comment]
Related with #341?

**Comment by vfportero** [comment]
Waiting to the BGStats owner approval

**Comment by jakejgordon** [comment]
@eerkov said he was fine with the content. I think there are just a couple of small things that he's working on in the app before it's ready to release entirely. Eerko, anything to add to that?

**Comment by eerkov** [comment]
Hi Jake,

Currently when posting from the app I receive the error 405: "The requested resource does not support http method 'GET’.”
I’ve tried it from a separate client as well, also with a POST request resulting in that error.

Is this something on your side?

Greetings,
Eerko

**Comment by eerkov** [comment]
Regarding release of the app version with Nemestats integration: I'm in the middle of some big statistical additions in the app, and I aim to release those together. I expect to finish these up mid-june, when I've got a vacation coming up to give it the right amount of momentum.
