### ISSUE TITLE
405 Method Not Allowed on API

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#408]
Per @eerkov 's comments on: https://github.com/NemeStats/NemeStats/issues/394 , we are getting a 405 method not allowed on API calls.

**Comment by jakejgordon** [comment]
@eerkov I'm having trouble recreating the issue. Can you give me an exact URI that you are using for a get request that doesn't require authentication. For example: both https://nemestats.com/api/v2/Players/?gamingGroupId=1 and https://nerdscorekeeper.azurewebsite.net/api/v2/Players/?gamingGroupId=1 work for me without issue. Please let me know if you have any more information and I'll check it out ASAP.

**Comment by jakejgordon** [comment]
Also, we now have https://nemestats.com working, so it would be best to switch to that endpoint -- although nerdscorekeeper.azurewebsite.net should work as well.

**Comment by eerkov** [comment]
I post to https://nerdscorekeeper.azurewebsites.net/api/v2/UserSessions/ with a valid username and password. Interestingly, when I with the URI to nemestats.com it does work.

**Comment by jakejgordon** [comment]
I was able to recreate this. Will try to get it resolved tomorrow. If you can, I'd switch to nemestats.com anyway.

**Comment by jakejgordon** [comment]
@eerkov -- I can recreate this in production but not in my development environment. If you can confirm that you are just going to use the the https://nemestats.com endpoint instead I probably won't spend any more time on this. However, if you are going to use nerdscorekeeper.azurewebsites.net then I'll keep investigating. Please confirm.

**Comment by jakejgordon** [comment]
Going to close this as "Won't Fix" since it doesn't look like anyone else is using the API yet and it is still easy to update the endpoint to https://nemestats.com. I can re-open if this presents an issue for BG Stats.
