### ISSUE TITLE
Try to Sort By Avg. Points per Game Messes Up Players Table

### ISSUE THREAD

**Issue by mike-koch** [NemeStats/NemeStats#414]
When viewing the main table at clicking on a column to sort by, the results no longer appear on page 1, and appear sparatically throughout the rest of the pages.

Before sort:
![screen shot 2016-05-23 at 9 22 34 pm](https://cloud.githubusercontent.com/assets/333430/15489282/7a458fc6-212c-11e6-92a1-4ab312f433fd.png)

After sort:
![screen shot 2016-05-23 at 9 22 41 pm](https://cloud.githubusercontent.com/assets/333430/15489298/8815981c-212c-11e6-8b29-ad44c429ad69.png)

**Comment by vfportero** [comment]
There are some sort problems on the "player with this achievement" table on achievement view
