### ISSUE TITLE
Ability to Record Multiple Games Quickly

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#419]
As a User who has saved up a bunch of games that I now need to record, I can have a way of recording a game and then remaining on the record a game page after each submit.

**Comment by vfportero** [comment]
How about to create a dummy "Success Page"?
This page could have 4 action buttons:

- Go to played game recorded
- Tweet this played game
- Go to gaming group
- Record new played game

**Comment by jakejgordon** [comment]
@vfportero I'm on the fence between just having a "Record another game?" checkbox on the record a game page vs. the separate page like you suggested. I like the idea of having other options available after submitting the game. My only concern is for those people who wants to record a bunch of games it really is just an extra step. I guess we could always do both -- and if they select the "Record another game" option it will bypass the success screen. Sound good?
