### ISSUE TITLE
As developer, I want that the current gaming groop url include the id to share purposes

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#439]
This URL: https://nemestats.com/GamingGroup must redirect to your GamingGroup details URL (in my case: https://nemestats.com/GamingGroup/Details/8268)

**Comment by jakejgordon** [comment]
Just be careful as there is technically an internal and external page so we obviously don't want to get the 2 mixed up. Maybe there is a way to route to a different action based on whether the user is authenticated with that Gaming Group?

**Comment by vfportero** [comment]
Yes, it's more complicated than I thought.
I'm trying to unify both views using a base view model with the common data and other viewmodel that inherit from the base with the rest of data.

With this and isolating parts of the view on Partials we can achieve one view for both cases.
