### ISSUE TITLE
Delete "zombie" players on Gaming Group

### ISSUE THREAD

**Issue by Hawke** [NemeStats/NemeStats#456]
Currently it is all too easy to accidentally create duplicate/extra players.

Please make it possible to merge or delete these extraneous players.

**Comment by jakejgordon** [comment]
If we start off with the ability to delete players that haven't participated in any played games would that be a good start? That would be easier than some of the alternatives.

**Comment by Hawke** [comment]
That seems reasonable as a start. Of course a merge is preferable in case you use both users already, or if one person in the group uses one name and a different user submits plays under another name.

**Comment by vfportero** [comment]
I think this is a two separated issued: Merge and Delete.

We can start with the option of deletion of "zombie" players and continue with the merge option some time in the future :)
