### ISSUE TITLE
Do not show the achievement unlocked date or progress when no user is logged

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#498]
![pasted image at 2016_09_13 07_30 am](https://cloud.githubusercontent.com/assets/1107782/18788846/c8380db2-81a8-11e6-8bb5-0411d0acc453.png)

**Comment by Serneum** [comment]
I think this applies to all achievements. Achievements that I don't have show that I will unlock them tomorrow. I assume it always shows the next day until you unlock it.

![image](https://cloud.githubusercontent.com/assets/1091716/18976958/47bb0c30-8684-11e6-9275-4a49632f532e.png)
