### ISSUE TITLE
Internal Server Error deleting user

### ISSUE THREAD

**Issue by jewelker** [NemeStats/NemeStats#501]
When I try to delete a user I get an error. I have tried de-activating the user. I also deleted all game plays with the user. I see that he is the nemesis for another user so I am guessing there is some kind of referential integrity setup on your database and the code does not account for this. 

While you look at this error, would it be possible for you to delete all of our Katy King Makers Board Game Group inactive users?  Thanks.

It might help to have better instructions. I am willing to help write these if you are interested. I am a customer success manager for a software company so maybe that skillset would help me to create a guide for the users to engage properly with this technology (nemestats plus bg stats)

I've been trying to coordinate the setup of our board game group with my buddy and we realized that we had created some duplicate entries. We are using BG Stats as well so the coordination and figuring out has taken some time.

**Comment by jakejgordon** [comment]
This is addressed in #502 . Closing.
