### ISSUE TITLE
Tons of duplicate BoardGameGeekGameCategory Records Getting Created

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#520]
Run the SQL query against a fairly recent instance of the production database and you'll see over 2,300 total records -- almost all of them duplicates.

SELECT [Id]
      ,[BoardGameGeekGameCategoryId]
      ,[CategoryName]
  FROM [NerdScorekeeper].[dbo].[BoardGameGeekGameCategory]
  ORDER BY BoardGameGeekGameCategoryId

We need to:
1. Add a unique constraint on BoardGameGeekGameCategoryId as well as another unique constraint on CategoryName (via attributes on the BusinessLogic model)
2. Add a migration to consolidate all references to this table to the single (oldest/original) id for the BoardGameGeekGameCategoryId and delete the duplicate records (via sql -- not code)

**Comment by vfportero** [comment]
It happens the same on BoardGameGeekGameMechanic...
