### ISSUE TITLE
Importing games from BGG is failing

### ISSUE THREAD

**Issue by Serneum** [NemeStats/NemeStats#529]
![image](https://cloud.githubusercontent.com/assets/1091716/20224438/77786b58-a80c-11e6-9c10-15bd5b4c9dda.png)

The progress bar gets information about the first game and then you get redirected to the error page.
`https://nemestats.com/GameDefinition/ImportFromBGG?Area=`

**Comment by Serneum** [comment]
Tried manually importing the game and got a popup that just said `error`. Game being imported is https://boardgamegeek.com/boardgame/193668/red-dragon-inn-battle-greyport

I was able to manually import https://boardgamegeek.com/boardgame/181523/snowblind-race-pole just fine.

**Comment by jakejgordon** [comment]
Definitely a major bug. Hoping to fix this shortly and get it deployed.

**Comment by jakejgordon** [comment]
Deployed in this release: https://github.com/NemeStats/NemeStats/releases/tag/2.56.2

**Comment by Serneum** [comment]
Confirmed that I can now import Battle for Greyport
