### ISSUE TITLE
Existing users are asked to register when clicking on group invite links

### ISSUE THREAD

**Issue by Serneum** [NemeStats/NemeStats#534]
I created a second NemeStats group (CMM #CLE Duels) and started inviting people from the main CMM #CLE group. When clicking on the invite link, they are being asked to register a new account

**Comment by jakejgordon** [comment]
Per slack conversation, these 3 invitations were sent to different email addresses than the users originally registered with. You'll need to send the invitation to the existing email address. Closing.
