### ISSUE TITLE
Incorrect Champion displaying for a game

### ISSUE THREAD

**Issue by kleric42** [NemeStats/NemeStats#574]
https://nemestats.com/GameDefinition/Details/38265

For this game, Chris S. was original champion.
Then Ash has won 2 games in a row, and should be champion, but Chris S. is still listed as the champion.

**Comment by jakejgordon** [comment]
It looks like this is an unintended side effect of the transactional component changes. Since the latest played game changes aren't saved to the DB by the time it recalculates champions, you have to record 2 games for the champion to update.

**Comment by jakejgordon** [comment]
Related to #412. issue will be fixed there.
