### ISSUE TITLE
Error when deleting player

### ISSUE THREAD

**Issue by lfaren** [NemeStats/NemeStats#584]
I'm running into an error when trying to delete a player (25793), https://nemestats.com/Player/Edit/25793. I have tried editing the name, thinking somehow a bad character ended up in the field. The player is marked as inactive.

Thanks!

**Comment by jakejgordon** [comment]
Thanks for letting us know. We'll check it out and let you know when it's fixed. It's definitely an issue on our end.

**Comment by jakejgordon** [comment]
Found the problem -- it had to do with players being a _previous_ champion but not taking care of the foreign key relationship to the game. his will get deployed soon.
