### ISSUE TITLE
I can't rename myself

### ISSUE THREAD

**Issue by Hawke** [NemeStats/NemeStats#615]
Someone invited me to a NemeStats group (https://nemestats.com/GamingGroup/Details/13501 ). I don't like how I'm listed there, so I'd like to rename myself. (https://nemestats.com/Player/Edit/21203 )

Unfortunately when I try, nemestats crashes with the following error: "Oh Crap! So... this is a little embarassing but it looks like nemestats.com just blew up in your face. We've logged the error so hopefully we'll fix it soon."

**Comment by jakejgordon** [comment]
Will try to fix this one soon. Thanks for reporting!

**Comment by Hawke** [comment]
Pretty sure it’s because there is already a player in the group by the same name.

**Comment by jakejgordon** [comment]
Finally got around to addressing this one. The fix will go out in the next deployment. Thanks again for taking the time to let us know about the issue.
