### ISSUE TITLE
Remember game type

### ISSUE THREAD

**Issue by Hawke** [NemeStats/NemeStats#616]
Currently if you go back to a previous play and edit it, Nemestats overrides the type to "ranked game". It should remember what the game type was. Ideally it would remember what type any given game normally is (e.g. "Brass" is always a scored game, while "Formula D" is nearly always ranked.

**Comment by Hawke** [comment]
In fact, "editing" a previous play simply loses all detail of the old play except the date. It would of course be much better to remember such things as players and scores so that you're actually *editing* the play not completely re-entering it.

**Comment by jakejgordon** [comment]
This should be resolved now. Closing.
