### ISSUE TITLE
Connexion to BGG lost since at least a week : UNABLE to add new games

### ISSUE THREAD

**Issue by Frenchwolfie** [NemeStats/NemeStats#718]
Hello, It's been more than a week since the loss of the connexion to BGG started and it's getting really annoying with time, to the point that I consider not to rely on Nemestats anymore in the future for my game statistics, starting in the next few days if nothing is done or no explanation given. Thank you for having a serious look into it, it seems that I'm not the only one inconvenienced.

**Comment by jakejgordon** [comment]
Hi there. BGG is blocking NemeStats at the moment and I don’t have time to look into it. If we can find another contributor that would be great. If not, then I don’t know when it will be fixed.

**Comment by Frenchwolfie** [comment]
Hi Jake, I took the liberty to write to Octavian, one of BGG administrators, to inquire into why it is so, and if there is no good reason for that, to make it work again. Let's hope.

Hello Matthew/Octavian, BGG used to support Nemestats (https://nemestats.com/) but since last week it seems it does not anymore - the links from it to BGG do not work anymore. It is a huge inconvenience for us Nemestats users. Is there a "good" reason for this state of affairs ? If not, could you make the link work again ? A BIG THANK YOU in advance.

Frenchwolfie

**Comment by Frenchwolfie** [comment]
From Octavian : Hi Frenchwolfie,

This isn't an issue of "supporting" or "not supporting", but more likely that nemestats was using our API and somewhere along the way that stopped working.

This isn't something we can do anything about without first knowing what broke on their end. Whoever runs the site needs to find out where that disconnect is and then email us that info at Contact@boardgamegeek.com so our developers can take a closer look.

**Comment by Frenchwolfie** [comment]
The problem seems to be solved, let's hope permanently. Thank you Jake
