### ISSUE TITLE
Unstable save playedgame

### ISSUE THREAD

**Issue by Nosceteipsum** [NemeStats/NemeStats#766]
I have issues with saving a playedgame session. 
It seems most of the time the service is down with an error code **500** and sometimes it just works again. :/ 

**Payload:**
__RequestVerificationToken: ekDp4stEpBXIanr6qMLoicvk6c-G8UAr9DjB-fCxec0Cin-eZSgyhVQCbY5FGDGkr9ythPZPEJuNrdqoHGwfnhksyZxWR7m7epBfr17f6Ep2i63YqGJ1ybE5EnBQ4i7hwJDqBHEoIq0FwNej9Z4deQ2
GameDefinitionId: 426241
GameDefinitionName: KLASK (2014)
Notes: 
DatePlayed: 2022-09-06
WinnerType: 1
PlayerRanks[0][PlayerId]: 84758
PlayerRanks[0][GameRank]: 2
PlayerRanks[0][PlayerName]: Willer
PlayerRanks[0][PointsScored]: 2
PlayerRanks[1][PlayerId]: 84275
PlayerRanks[1][GameRank]: 1
PlayerRanks[1][PlayerName]: TommyAndersen (me)
PlayerRanks[1][PointsScored]: 6
EditMode: false

**Result:**
![image](https://user-images.githubusercontent.com/7213547/188853079-c32ce517-0c56-4c07-a61e-01c8c4a3dd2b.png)

**Comment by HolisticDeveloper** [comment]
I'm hoping to get contributor access soon so I can look into this one.

**Comment by HolisticDeveloper** [comment]
@Nosceteipsum This may be resolved now. I was getting similar errors due to the database being full. I've allocated more space for it and the error went away for me.

**Comment by HolisticDeveloper** [comment]
I will go ahead and close this one. Let us know if you see it come up again.
